














































































































































































export const withdrawalRoutes = router;app.use(databaseErrorHandler);// Make sure this is added after all route registrationsrouter.post('/', authenticate, withdrawalValidation, validate, withdrawalController.withdraw);];    .withMessage('SWIFT code is required for wire transfers')    .notEmpty()    .if(body('withdrawalMethod').equals('Wire Transfer'))  body('swiftCode')    .withMessage('Account number is required'),    .notEmpty()  body('accountNumber')    .withMessage('Invalid withdrawal method'),    .isIn(['Bank Transfer', 'Wire Transfer', 'Cryptocurrency'])  body('withdrawalMethod')    .withMessage('Amount must be greater than 0'),    .isFloat({ min: 0.01 })  body('amount')const withdrawalValidation = [ */ *         description: Server error *       500: *                       example: 403 *                       type: number *                     code: *                       example: "KYC verification required for withdrawals" *                       type: string *                     message: *                   properties: *                   type: object *                 error: *                   example: false *                   type: boolean *                 success: *               properties: *               type: object *             schema: *           application/json: *         content: *         description: KYC verification or active card required *       403: *         description: Not authenticated *       401: *                       example: 400 *                       type: number *                     code: *                       example: "Insufficient balance" *                       type: string *                     message: *                   properties: *                   type: object *                 error: *                   example: false *                   type: boolean *                 success: *               properties: *               type: object *             schema: *           application/json: *         content: *         description: Invalid request or insufficient balance *       400: *               $ref: '#/components/schemas/WithdrawalResponse' *             schema: *           application/json: *         content: *         description: Withdrawal processed successfully *       200: *     responses: *             $ref: '#/components/schemas/WithdrawalRequest' *           schema: *         application/json: *       content: *       required: true *     requestBody: *       - bearerAuth: [] *     security: *     tags: [Withdrawals] *       - Sufficient balance *       - Active card *       - Approved KYC verification *       - Authenticated user *       Submit a withdrawal request. Requires: *     description: | *     summary: Process a withdrawal request *   post: * /api/withdrawals: * @swagger/** */ *               description: HTML formatted receipt *               type: string *             receipt: *                   example: 49000.00 *                   type: number *                 balanceAfter: *                   example: "TXN202401201234567" *                   type: string *                 reference: *                   example: "processing" *                   type: string *                 status: *                   example: 1000.00 *                   type: number *                 amount: *                   example: "withdrawal" *                   type: string *                 type: *                   example: "507f1f77bcf86cd799439011" *                   type: string *                 id: *               properties: *               type: object *             transaction: *           properties: *           type: object *         data: *           example: true *           type: boolean *         success: *       properties: *       type: object *     WithdrawalResponse: *           example: "BOFAUS3N" *           description: SWIFT code (required for Wire Transfer) *           type: string *         swiftCode: *           example: "1234567890" *           description: Recipient account number *           type: string *         accountNumber: *           example: Bank Transfer *           description: Method of withdrawal *           enum: [Bank Transfer, Wire Transfer, Cryptocurrency] *           type: string *         withdrawalMethod: *           example: 1000.00 *           description: Amount to withdraw *           minimum: 0.01 *           type: number *         amount: *       properties: *         - accountNumber *         - withdrawalMethod *         - amount *       required: *       type: object *     WithdrawalRequest: *   schemas: * components: * @swagger/** */ *   description: Withdrawal management endpoints *   name: Withdrawals * tags: * @swagger */**const router = express.Router();import { databaseErrorHandler } from './middleware/databaseErrorHandler.js';import { body } from 'express-validator';import { validate } from '../middleware/validate.js';import { authenticate } from '../middleware/authenticate.js';import { withdrawalController } from '../controllers/withdrawalController.js';import express from 'express';